site_name: Web Scraping Pipeline Docs
site_url: https://lnynhi02.github.io/web-scraping-pipeline-docs

extra_css:
  - stylesheets/extra.css

nav:
  - Deployment: deployment.md
  - Technical Documentation: index.md
  - GitHub Repository: https://github.com/lnynhi02/web-scraping-etl-pipeline

theme:
  name: material

  features:
    - navigation.sections
    - navigation.top

  palette: 
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tasklist